In [1]:
# Matrix Operations in NumPy for Machine Learning

# 1. Import libraries
import numpy as np
import matplotlib.pyplot as plt

# ---

# ## 1. Matrix Creation

# Create a 2x3 matrix
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print("Matrix A:\n", A)

# ---

# ## 2. Matrix Shape and Reshaping

# Check shape
print("Shape of A:", A.shape)

# Reshape A to a 3x2 matrix
A_reshaped = A.reshape(3, 2)
print("Reshaped A:\n", A_reshaped)

# ---

# ## 3. Matrix Addition and Subtraction

# Create another matrix B of the same shape
B = np.array([[7, 8, 9],
              [10, 11, 12]])

# Element-wise addition
C = A + B
print("A + B =\n", C)

# Element-wise subtraction
D = A - B
print("A - B =\n", D)

# ---

# ## 4. Scalar Multiplication

# Multiply A by scalar 2
E = 2 * A
print("2 * A =\n", E)

# ---

# ## 5. Matrix Multiplication (Dot Product)

# Matrix multiplication (dot product)
# A: (2,3) and F: (3,2) => result (2,2)
F = np.array([[1, 2],
              [3, 4],
              [5, 6]])

G = np.dot(A, F)
print("A dot F =\n", G)

# ---

# ## 6. Element-wise Multiplication

# Element-wise multiplication
H = A * B
print("Element-wise multiplication A * B =\n", H)

# ---

# ## 7. Transpose of a Matrix

# Transpose of A
A_T = A.T
print("Transpose of A:\n", A_T)

# ---

# ## 8. Inverse of a Matrix

# Create a 2x2 matrix
M = np.array([[4, 7],
              [2, 6]])

# Find inverse
M_inv = np.linalg.inv(M)
print("Inverse of M:\n", M_inv)

# Verify: M * M_inv should be identity
print("M * M_inv =\n", np.dot(M, M_inv))

# ---

# ## 9. Identity Matrix

# Create 3x3 identity matrix
I = np.eye(3)
print("Identity matrix:\n", I)

# ---

# ## 10. Determinant of a Matrix

# Determinant of M
det_M = np.linalg.det(M)
print("Determinant of M:", det_M)

# ---

# End of notebook.


Matrix A:
 [[1 2 3]
 [4 5 6]]
Shape of A: (2, 3)
Reshaped A:
 [[1 2]
 [3 4]
 [5 6]]
A + B =
 [[ 8 10 12]
 [14 16 18]]
A - B =
 [[-6 -6 -6]
 [-6 -6 -6]]
2 * A =
 [[ 2  4  6]
 [ 8 10 12]]
A dot F =
 [[22 28]
 [49 64]]
Element-wise multiplication A * B =
 [[ 7 16 27]
 [40 55 72]]
Transpose of A:
 [[1 4]
 [2 5]
 [3 6]]
Inverse of M:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
M * M_inv =
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Determinant of M: 10.000000000000002
