In [1]:
!pip install torch

Defaulting to user installation because normal site-packages is not writeable

[notice] A new release of pip is available: 25.0.1 -> 25.1.1
[notice] To update, run: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m pip install --upgrade pip


In [7]:
import torch
x = torch.tensor([1,2,3,4,5])
y = torch.tensor([4,5,6,7, 8])

In [8]:
x * y

tensor([ 4, 10, 18, 28, 40])

In [16]:
torch.arange(1,51).view(2,25)

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
         19, 20, 21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
         44, 45, 46, 47, 48, 49, 50]])

In [17]:
x.requires_grad # grad

False

In [19]:
x = torch.tensor([2.0], requires_grad=True )

In [20]:
x.requires_grad

True

In [23]:
y = x**2 + 3*x + 1

In [24]:
y.backward()

In [25]:
x.grad

tensor([7.])

In [26]:
import torch.nn as nn


In [27]:
nn

<module 'torch.nn' from '/Users/lexai/Library/Python/3.9/lib/python/site-packages/torch/nn/__init__.py'>

In [31]:
linear_layer = nn.Linear(in_features=3, out_features=2)

In [34]:
input_tensor = torch.randn(5,3)

In [35]:
input_tensor

tensor([[-0.6235, -1.0672,  1.0466],
        [ 0.0021,  0.6256, -0.2005],
        [-0.1815, -0.3361, -1.5565],
        [-0.4225,  0.4530, -1.0513],
        [-1.6682,  0.1906, -0.4184]])

In [36]:
torch.sigmoid(x)

tensor([0.8808], grad_fn=<SigmoidBackward0>)

In [37]:
import torch.nn.functional as F

In [38]:
F

<module 'torch.nn.functional' from '/Users/lexai/Library/Python/3.9/lib/python/site-packages/torch/nn/functional.py'>

In [39]:
torch.__version__

'2.7.1'

In [42]:
torch.cuda.is_available()

False

In [48]:
linear_layer

Linear(in_features=3, out_features=2, bias=True)

In [49]:
output = linear_layer(input_tensor)

In [50]:
output

tensor([[-0.8730, -0.3368],
        [-0.1879,  0.1784],
        [-1.2857, -0.4378],
        [-0.7998, -0.0994],
        [-1.2739, -0.2915]], grad_fn=<AddmmBackward0>)

In [53]:
# relu, tanh, softmax, convolution, pooling, dropout layers. 

tensor([0.9640], grad_fn=<TanhBackward0>)

In [66]:
nn.Sequential(nn.Linear(784,128), nn.ReLU(), nn.Dropout(0.1), nn.Linear(128, 128), nn.Softmax(), nn.Linear(128, 10), nn.Softmax(dim=1))

Sequential(
  (0): Linear(in_features=784, out_features=128, bias=True)
  (1): ReLU()
  (2): Dropout(p=0.1, inplace=False)
  (3): Linear(in_features=128, out_features=128, bias=True)
  (4): Softmax(dim=None)
  (5): Linear(in_features=128, out_features=10, bias=True)
  (6): Softmax(dim=1)
)